alter FUNCTION [dbo].udf_siteKey (
	@site_name varchar(4000)
)
RETURNS  varchar(4000)
    WITH EXECUTE AS CALLER
AS
    begin
		declare @finalSiteName varchar(4000)
		set @finalSiteName = replace(case
				when ( @site_name like '%[Cc]hicago%[Tt]ribune%' or @site_name like '[Tt]ribune_[Ii]nteractive%' ) then 'ChicagoTribune'
				when ( @site_name like '[Gg][Dd][Nn]%' or @site_name like '[Gg]oogle_[Dd]isplay_[Nn]etwork%' or @site_name = 'Google' or @site_name like '%Google%' or @site_name like '%DBM%' or @site_name like '%[Dd][Oo][Uu][Bb][Ll][Ee][Cc][Ll][Ii][Cc][Kk]%') then 'Google'
				when @site_name like '%[Aa]dara%' then 'Adara'
				when @site_name like '%[Aa]tlantic%' then 'The Atlantic'
				when @site_name like '%[Bb]usiness%[Ii]nsider%' then 'Business Insider'
				when @site_name like '%[Cc][Nn][Nn]%' then 'CNN'
				when @site_name like '%[Ee][Ss][Pp][Nn]%' then 'ESPN'
				when @site_name like '%[Ff]orbes%' then 'Forbes'
				when @site_name like '%[Gg]olf%[Dd]igest%' then 'GolfDigest'
				when @site_name like '%[Jj]un%[Gg]roup%' then 'JunGroup'
				when @site_name like '%[Mm][Ll][Bb]%' then 'MLB'
				when @site_name like '%[Mm]ansueto%' or @site_name like '[Ii][Nn][Cc]%' then 'Inc'
				when @site_name like '%[Mn][Ss][Nn]%' then 'MSN'
				when @site_name like '%[Nn][Bb][Aa]%' then 'NBA'
				when @site_name like '%[Nn][Ff][Ll]%' then 'NFL'
				when @site_name like '%[Nn]ast%[Tt]raveler%' then 'CN Traveler'
				when @site_name like '%[Nn]ew%[Yy]ork%[Tt]imes%' or @site_name like '%[Nn]ew[Yy]ork[Tt]imes%' or @site_name like '%[Nn][Yy][Tt]imes%' then 'NYTimes'
				when @site_name like '%[Nn]ew%[Yy]orker%' then 'New Yorker'
				when @site_name like '%[Pp]andora%' then 'Pandora'
				when @site_name like '%[Pp][Gg][Aa]%[Tt][Oo][Uu][Rr]%' then 'PGATour'
				when @site_name like '%[Pp]eople%' and @site_name like '%[Ee]spa[nñ]ol%' then 'People En Espanol'
				when @site_name like '%[Pp]riceline%' then 'Priceline'
				when @site_name like '%[Ss]ports%[Ii]llustrated%' then 'Sports Illustrated'
				when @site_name like '%[Tt]ap%[Aa]d%' then 'TapAd'
				when @site_name like '%[Tt]ime%[Oo]ut%' then 'Time Out New York'
				when @site_name like '%[Tt]ravel%[Ll]eisure%' then 'TravelLeisure'
				when @site_name like '%[Tt]hrillist%' then 'Thrillist'
				when @site_name like '%[Uu]ber%' then 'Uber'
				when @site_name like '%[Uu]ndertone%' then 'Undertone'
				when @site_name like '%[Ww]all%[Ss]treet%[Jj]ournal%' or @site_name like '[Ww][Ss][Jj]' then 'Wall Street Journal'
				when @site_name like '%[Ww]ashington%[Pp]ost%' then 'Washington Post'
				when @site_name like '%[Yy]ahoo%' then 'Yahoo'
				when @site_name like '%[Yy]ou%[Tt]ube%' then 'YouTube'
				when @site_name like '[Aa][Ss][Tt][Aa]%' then 'ASTA'
				when @site_name like '[Aa]d[Pp]rime%' then 'AdPrime'
				when @site_name like '[Aa]ds[Mm]ovil%' then 'AdsMovil'
				when @site_name like '[Aa]mobee%' then 'Amobee'
				when @site_name like '[Bb]usiness%[Tt]ravel%' then 'Business Travel News'
				when @site_name like '[Bb]loomberg%' then 'Bloomberg'
				when @site_name like '[Cc]ardlytics%' then 'Cardlytics'
				when @site_name like '[Dd][Aa][Rr][Tt]%Search%Google' then 'DART Search_Google'
				when @site_name like '[Dd][Aa][Rr][Tt]%Search%MSN' then 'DART Search_MSN'
				when @site_name like '[Dd][Aa][Rr][Tt]%Search%Other' then 'DART Search_Other'
				when @site_name like '[Ee]xponential%' then 'Exponential'
				when @site_name like '[Ee]xpedia%' then 'Expedia'
				when @site_name like '[Ff]acebook%' then 'Facebook'
				when @site_name like '[Ff]ast%[Cc]ompany%' then 'Fast Company'
				when @site_name like '[Ff]inancial%[Tt]imes%' then 'FinancialTimes'
				when @site_name like '[Gg]um%[Gg]um%' or @site_name like '[Gg]um[Gg]um%' then 'Gum Gum'
				when @site_name like '[Hh]ulu%' then 'Hulu'
				when @site_name like '[Ii][Nn][Vv][Ii][Tt][Ee]%[Mm][Ee][Dd][Ii][Aa]%' then 'Invite Media'
				when @site_name like '[Ii]mpre%[Mm]edia%' then 'Impre Media'
				when @site_name like '[Ii]ndependent%' then 'Independent'
				when @site_name like '[Ii]nternet%[Bb]rands%' then 'Internet Brands'
				when @site_name like '[Jj]i[Ww]ire%' or @site_name like '%[Nn]inth%[Dd]ecimal%' then 'Ninth Decimal'
				when @site_name like '[Kk]ayak%' then 'Kayak'
				when @site_name like '[Ll]ive%[Ii]ntent%' or @site_name like '[Ll]ive[Ii]ntent%' then 'LiveIntent'
				when @site_name like '[Mm]artini%' then 'Martini Media'
				when @site_name like '[Nn]ew%[Yy]ork%[Mm]ag%' then 'NewYorkMagazine'
				when @site_name like '[Oo]rbitz%' then 'Orbitz'
				when @site_name like '[Pp][Cc][Mm][Aa]%' then 'PCMA'
				when @site_name like '[Qq]uartz%' then 'Quartz'
				when @site_name like '[Qq]uantcast%' then 'Quantcast'
				when @site_name like '[Ss]kyscanner%' then 'Skyscanner'
				when @site_name like '[Ss]mart%[Bb]r[ei][ei]f%' then 'SmartBrief'
				when @site_name like '[Ss]marter%[Tt]ravel%' then 'Trip Advisor'
				when @site_name like '[Ss]mithsonian%' then 'Smithsonian'
				when @site_name like '[Ss]ojern%' then 'Sojern'
				when @site_name like '[Ss]pecific%[Mm]edia%' or @site_name like '[Vv]iant%' then 'Viant'
				when @site_name like '[Ss]potify%' then 'Spotify'
				when @site_name like '[Tt]ime%[Ii]nc%' then 'Time Inc'
				when @site_name like '[Tt]ony%[As]wards%' then 'TonyAwards'
				when @site_name like '[Tt]ravel%[Ss]pike%' or @site_name like '[Tt]ravel[Ss]pike%' then 'Travel Spike'
				when @site_name like '[Tt]ravel[Mm]arket[Rr]eport%' then 'TMR'
				when @site_name like '[Tt]ravelocity%' then 'Travelocity'
				when @site_name like '[Tt]riggit%' then 'Triggit'
				when @site_name like '[Tt]rip%[Aa]dvisor%' then 'Trip Advisor'
				when @site_name like '[Uu]nited%' then 'United'
				when @site_name like '[Vv]erve%' then 'Verve'
				when @site_name like '[Vv]istar%[Mm]edia%' or @site_name like '[Vv]istar[Mm]edia%' then 'VistarMedia'
				when @site_name like '[Vv]ox%' then 'Vox'
				when @site_name like '[Ww]ired%' then 'Wired'
				when @site_name like '[Xx][Aa][Xx][Ii][Ss]%' then 'Xaxis'
				when @site_name like '[Xx]ad%' then 'xAd Inc'
				when @site_name like '[Yy]ieldbot%' then 'Yieldbot'
				when @site_name like '[Yy]u[Mm]e%' then 'YuMe'
			  when @site_name like '[Ff]lipboard%' then 'Flipboard'
        when @site_name like '[Gg][Bb][Tt][Aa]%' then 'GBTA'
        when @site_name like '[Ss][Uu][Cc][Cc][Ee][Ss][Ss][Ff][Uu][Ll][Mm][Ee][Ee][Tt][Ii][Nn][Gg][Ss]%' then 'NorthStar'
      	when @site_name like '[Pp]ad[Ss]quad%' then 'PadSquad'
				when @site_name like '[Oo]gury%' then 'Ogury'
				when @site_name like '[Rr]euters%' then 'Reuters'
				when @site_name like '[Vv]isible%[Mm]easures%' then 'Visible Measures'
				when @site_name like '[Cc]aptify%' then 'Captify'
        when @site_name like '[Tt]ravel[Ww]eekly%' then 'Travel Weekly'
			  when @site_name like '[Pp]lace%[Ii][Qq]%' then 'Place IQ'


				else @site_name end
				,' ','');
RETURN @finalSiteName
end
